<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-RG5BBFG9" name="myAccountPageTests.VerifyAllStatesWithErrorsInAddressBook" tests="2" failures="2" timestamp="14 Sep 2021 16:47:04 GMT" time="996.760" errors="0">
  <testcase name="verifyAllStatesWithErrorsInAddressBook" time="537.282" classname="myAccountPageTests.VerifyAllStatesWithErrorsInAddressBook">
    <failure type="java.lang.AssertionError" message="Fail: There are States with error:[AA, AE, AP, AS, AE, GU, MP, UM]">
      <![CDATA[java.lang.AssertionError: Fail: There are States with error:[AA, AE, AP, AS, AE, GU, MP, UM]
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.BaseTestClass.reportFail(BaseTestClass.java:154)
	at myAccountPageTests.VerifyAllStatesWithErrorsInAddressBook.verifyAllStatesWithErrorsInAddressBook(VerifyAllStatesWithErrorsInAddressBook.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- verifyAllStatesWithErrorsInAddressBook -->
  <testcase name="verifyAllStatesWithErrorsInAddressBook" time="459.478" classname="myAccountPageTests.VerifyAllStatesWithErrorsInAddressBook">
    <failure type="java.lang.AssertionError" message="timeout: Timed out receiving message from renderer: 30.000
  (Session info: chrome=93.0.4577.63)
Build info: version: &#039;4.0.0-rc-1&#039;, revision: &#039;bc5511cbda&#039;
System info: host: &#039;LAPTOP-RG5BBFG9&#039;, ip: &#039;192.168.1.6&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_291&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c8e11a858167c342e808faaa6d83232e, clickElement {id=d97fd826-45de-4af5-86ab-cba9b11e000c}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 93.0.4577.63, chrome: {chromedriverVersion: 93.0.4577.15 (660fc11082ba5..., userDataDir: C:\Users\AJAY\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:51132}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51132/devtoo..., se:cdpVersion: 93.0.4577.63, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (c8e11a858167c342e808faaa6d83232e)] -&gt; xpath: //*[@id=&#039;BreadcrumbTopContainer&#039;]//a[contains(text(),&#039;Home&#039;)]]
Session ID: c8e11a858167c342e808faaa6d83232e">
      <![CDATA[java.lang.AssertionError: timeout: Timed out receiving message from renderer: 30.000
  (Session info: chrome=93.0.4577.63)
Build info: version: '4.0.0-rc-1', revision: 'bc5511cbda'
System info: host: 'LAPTOP-RG5BBFG9', ip: '192.168.1.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c8e11a858167c342e808faaa6d83232e, clickElement {id=d97fd826-45de-4af5-86ab-cba9b11e000c}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 93.0.4577.63, chrome: {chromedriverVersion: 93.0.4577.15 (660fc11082ba5..., userDataDir: C:\Users\AJAY\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:51132}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:51132/devtoo..., se:cdpVersion: 93.0.4577.63, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (c8e11a858167c342e808faaa6d83232e)] -> xpath: //*[@id='BreadcrumbTopContainer']//a[contains(text(),'Home')]]
Session ID: c8e11a858167c342e808faaa6d83232e
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.BaseTestClass.reportFail(BaseTestClass.java:154)
	at PageClasses.MyAccountPage.clickHomeLink(MyAccountPage.java:1143)
	at myAccountPageTests.VerifyAllStatesWithErrorsInAddressBook.verifyAllStatesWithErrorsInAddressBook(VerifyAllStatesWithErrorsInAddressBook.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- verifyAllStatesWithErrorsInAddressBook -->
</testsuite> <!-- myAccountPageTests.VerifyAllStatesWithErrorsInAddressBook -->
